### ISSUE TITLE
Add new best practise in group page?

### ISSUE THREAD

**Issue by poVoq** [ColdTrick/best_practices#1]
Seems like it is only possible to add a best practice in the site section.

Would be nice if it was possible to add one in the group view with the related group automatically added.

**Comment by jdalsem** [comment]
This plugin behaves a bit strange regarding to groups. You can "link" best practices to groups, but not add them to groups. If you link them, you can show them in a widget on the group. This behaviour is not "normal" Elgg, but a client specific wish.
