### ISSUE TITLE
Can not add group widget

### ISSUE THREAD

**Issue by poVoq** [ColdTrick/best_practices#3]
When trying to add an best practise group widget the following elgg error is shown:
"We could not add your widget."

**Comment by jdalsem** [comment]
is your default acces by any change private?

**Comment by poVoq** [comment]
No, all default elgg settings, i.e. public access by default.

**Comment by jdalsem** [comment]
which version of widget manager are you using?

**Comment by poVoq** [comment]
latest 4.8

**Comment by poVoq** [comment]
Another strange thing is that I can't manage that widget in the administrator interface like the other widgets (I can not for example hide it). It just doesn't show up in the admin interface at all.

**Comment by jdalsem** [comment]
Closing as being unable to reproduce
