### ISSUE TITLE
When logged out profile menu is visible

### ISSUE THREAD

**Issue by poVoq** [ColdTrick/best_practices#4]
When viewing a best practice and one is not logged in the profile menu of the entity owner is visible at the top of the side-bar.

This makes it a bit confusing with the contact directly below (especially if it isn't identical to the entity owner) and also seems unnecessary screen clutter for this function.

**Comment by jeabakker** [comment]
this is default behaviour of Elgg, is you set the page_owner the sidebar info will be shown
